### PR TITLE
Stackage LTS 15 and Repaired CI

### LINKED ISSUE #74: Doesn't build with GHC-8.8.1/base-4.13
```
Build profile: -w ghc-8.8.1 -O0
In order, the following will be built (use -v for more details):
 - sqlite-simple-0.4.16.0 (lib) (first run)
Configuring library for sqlite-simple-0.4.16.0..
Preprocessing library for sqlite-simple-0.4.16.0..
Building library for sqlite-simple-0.4.16.0..
[ 1 of 11] Compiling Database.SQLite.Simple.Ok ( Database/SQLite/Simple/Ok.hs, /code/mess/sqlite-simple/sqlite-simple-0.4.16.0/.dist-newstyle-trustee/5e7d9fd33a5064be14b944e0c13b8f4b86cbfea5c40b9a2fedcf90f6574fd737601d0660b79d714d2285991de221c3fd383f34af92592b8382c7510520aa0702/build/x86_64-linux/ghc-8.8.1/sqlite-simple-0.4.16.0/noopt/build/Database/SQLite/Simple/Ok.o )


Database/SQLite/Simple/Ok.hs:75:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
75 |     fail str = Errors [SomeException (ErrorCall str)]
   |     ^^^^
```

```
Build profile: -w ghc-8.8.1 -O0
In order, the following will be built (use -v for more details):
 - sqlite-simple-0.4.15.0 (lib) (first run)
Configuring library for sqlite-simple-0.4.15.0..
Preprocessing library for sqlite-simple-0.4.15.0..
Building library for sqlite-simple-0.4.15.0..
[ 1 of 10] Compiling Database.SQLite.Simple.Ok ( Database/SQLite/Simple/Ok.hs, /code/mess/sqlite-simple/sqlite-simple-0.4.15.0/.dist-newstyle-trustee/5e7d9fd33a5064be14b944e0c13b8f4b86cbfea5c40b9a2fedcf90f6574fd737601d0660b79d714d2285991de221c3fd383f34af92592b8382c7510520aa0702/build/x86_64-linux/ghc-8.8.1/sqlite-simple-0.4.15.0/noopt/build/Database/SQLite/Simple/Ok.o )


Database/SQLite/Simple/Ok.hs:75:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
75 |     fail str = Errors [SomeException (ErrorCall str)]
   |     ^^^^
```

I also made revisions to affected versions on Hackage

- https://hackage.haskell.org/package/sqlite-simple-0.4.16.0/revisions/ 
- https://hackage.haskell.org/package/sqlite-simple-0.4.15.0/revisions/

### PR DESCRIPTION
**Pull request by fosskers**
Building off of https://github.com/IreneKnapp/direct-sqlite/pull/82 , this is the next step in getting `beam` into LTS 15 as well.

**This PR also fixes imports such that CI works again.**

Closes #74 
Closes #75 
Closes #77

### CODE REVIEW

File: stack.yaml [hunk 1]
```diff
@@ -1 +1,4 @@
-resolver: lts-11.9
+resolver: lts-15.1
+
+extra-deps:
+  - direct-sqlite-2.3.26
```
Comment (fosskers) [inline stack.yaml]: A fresh release from today, hence it needs to be pinned here to prove compatibility.

**Comment by sigrlami** [comment]
@fosskers awesome! I'll check it locally and most probably will merge and prepare release tomorrow.

**Comment by sigrlami** [comment]
lgtm!
