### ISSUE TITLE
Getting ambiguous occurrence `fail`?

### ISSUE THREAD

**Issue by danwdart** [nurpax/sqlite-simple#100]
```
Building library for sqlite-simple-0.4.18.1..
[ 1 of 12] Compiling Database.SQLite.Simple.Ok ( Database/SQLite/Simple/Ok.hs, dist/build/Database/SQLite/Simple/Ok.o )

Database/SQLite/Simple/Ok.hs:86:14: error:
    Ambiguous occurrence ‘fail’
    It could refer to either ‘Prelude.fail’,
                             imported from ‘Prelude’ at Database/SQLite/Simple/Ok.hs:31:8-32
                             (and originally defined in ‘GHC.Base’)
                          or ‘Control.Monad.Fail.fail’,
                             imported from ‘Control.Monad.Fail’ at Database/SQLite/Simple/Ok.hs:40:1-25
   |
86 |     throwM = fail . show
```

I'm not sure why this might suddenly be happening, since revision 49390582cb090fc1ef95988dab9ecc8ebb32251b.

Building on ghc 8.6.5

Thanks!

**Comment by jchia** [comment]
Do you still need GHC 8.6 support? It's very old. We don't test with 8.6 nowadays. If you still need sqlite-simple to work with 8.6, do you have a general fix that works and is elegant for 8.6 and later versions (i.e. that does not resort to differentiating for version 8.6)?

**Comment by danwdart** [comment]
I'm not sure why I needed it before. I certainly don't now. Let's ignore, cheers
