### ISSUE TITLE
Doesn't build with GHC-8.8.1/base-4.13

### ISSUE THREAD

**Issue by phadej** [nurpax/sqlite-simple#74]
```
Build profile: -w ghc-8.8.1 -O0
In order, the following will be built (use -v for more details):
 - sqlite-simple-0.4.16.0 (lib) (first run)
Configuring library for sqlite-simple-0.4.16.0..
Preprocessing library for sqlite-simple-0.4.16.0..
Building library for sqlite-simple-0.4.16.0..
[ 1 of 11] Compiling Database.SQLite.Simple.Ok ( Database/SQLite/Simple/Ok.hs, /code/mess/sqlite-simple/sqlite-simple-0.4.16.0/.dist-newstyle-trustee/5e7d9fd33a5064be14b944e0c13b8f4b86cbfea5c40b9a2fedcf90f6574fd737601d0660b79d714d2285991de221c3fd383f34af92592b8382c7510520aa0702/build/x86_64-linux/ghc-8.8.1/sqlite-simple-0.4.16.0/noopt/build/Database/SQLite/Simple/Ok.o )


Database/SQLite/Simple/Ok.hs:75:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
75 |     fail str = Errors [SomeException (ErrorCall str)]
   |     ^^^^
```

```
Build profile: -w ghc-8.8.1 -O0
In order, the following will be built (use -v for more details):
 - sqlite-simple-0.4.15.0 (lib) (first run)
Configuring library for sqlite-simple-0.4.15.0..
Preprocessing library for sqlite-simple-0.4.15.0..
Building library for sqlite-simple-0.4.15.0..
[ 1 of 10] Compiling Database.SQLite.Simple.Ok ( Database/SQLite/Simple/Ok.hs, /code/mess/sqlite-simple/sqlite-simple-0.4.15.0/.dist-newstyle-trustee/5e7d9fd33a5064be14b944e0c13b8f4b86cbfea5c40b9a2fedcf90f6574fd737601d0660b79d714d2285991de221c3fd383f34af92592b8382c7510520aa0702/build/x86_64-linux/ghc-8.8.1/sqlite-simple-0.4.15.0/noopt/build/Database/SQLite/Simple/Ok.o )


Database/SQLite/Simple/Ok.hs:75:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
75 |     fail str = Errors [SomeException (ErrorCall str)]
   |     ^^^^
```

I also made revisions to affected versions on Hackage

- https://hackage.haskell.org/package/sqlite-simple-0.4.16.0/revisions/ 
- https://hackage.haskell.org/package/sqlite-simple-0.4.15.0/revisions/

**Comment by sigrlami** [comment]
@phadej hi, thanks. I'll take a look into it on a weekend, update and publish.

**Comment by phadej** [comment]
https://gitlab.haskell.org/ghc/ghc/wikis/proposal/monad-fail#adapting-old-code is handy, if you are not familiar with the issue

**Comment by gwils** [comment]
@sigrlami Have you had a chance to look at this?
